providers = ['staticfile']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1731369831'

[variables]
NIXPACKS_METADATA = 'rust'

[phases.setup]
nixPkgs = [
    '...',
    'binutils',
    'gcc',
    '(rust-bin.fromRustupToolchainFile ../rust-toolchain.toml)',
    'trunk',                                                     # used to buidl wasm
]
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
nixpkgsArchive = '8d48200ead5adea71485965f92405575c66dab04'
onlyIncludeFiles = ['rust-toolchain.toml']

[phases.build]
dependsOn = ['setup']
cmds = ['trunk build --release --frozen --locked --minify']
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry', 'target']

[start]
runImage = 'debian:bullseye-slim'
onlyIncludeFiles = ['./dist']
