providers = ['rust', 'staticfile']

[phases."staticfile:setup"]
onlyIncludeFiles = ['./nginx.conf']
nixpkgsArchive = '8d48200ead5adea71485965f92405575c66dab04'

[phases.setup]
nixPkgs = [
    '...',
    'trunk', # used to buidl wasm
]
nixpkgsArchive = '8d48200ead5adea71485965f92405575c66dab04'

[phases.build]
cmds = ['trunk build --release --frozen --locked --minify']


[start]
cmd = "nginx -c /app/nginx.conf"
runImage = 'nginx:1.27.2'
onlyIncludeFiles = ['/app/dist', '/app/nginx.conf']
